image: node

# Cache node modules - speeds up future builds
cache:
  paths:
  - node_modules

stages:
  - test
  - build
  - deploy

test:
  stage: test
  script: echo "Running tests"

build:
  stage: build
  script: echo "Building the app"
    - npm install
    - npm run build

deploy_staging:
  stage: deploy
  script: echo "Deploy to staging server"
  environment:
    name: staging
    url: https://stagiss.manumac.com.ar
  only:
  - master

deploy_prod:
  stage: deploy
  script: echo "Deploy to production server"
  environment:
    name: production
    url: https://iss.manumac.com.ar
  when: manual
  only:
  - master