image: node

# Cache node modules - speeds up future builds
cache:
  paths:
  - node_modules

stages:
  - install
  - test
  - build
  - deploy

install-dependencies: 
  stage: install
  script: 
    - npm install
  artifacts:
    expire_in: 1hr
    paths:
      - node_modules

test:
  stage: test
  script: echo "Running tests"

build:
  stage: build
  dependencies: 
    - install-dependencies
  script:
    - npm run build:prod
    - ls -l
  artifacts:
    expire_in: 1hr
    paths: 
      - dist/
pages: 
  stage: deploy
  dependencies: 
    - build
  script: 
    - mkdir public
    - ls -l
    - mv dist/* public
  artifacts:
    paths:
      - public
  environment:
    name: stage
  only: 
    - branches